version: "3.8"

services:
  web:
    build: ./app
    container_name: back-login
    volumes:
      - ./app:/app  # Mapea todo el proyecto Django
      - ./app/media:/app/media  # Mapeo específico para media  # Monta la carpeta media como volumen
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    networks:
      - app-network
    command: python /app/manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    container_name: front-vite
    volumes:
      - ./frontend:/app  # Monta la carpeta frontend local en /app del contenedor
      - /app/node_modules  # Evita conflictos con node_modules en el host
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - web

networks:
  app-network:
    driver: bridge
