services:
  web:
    build: ./app
    container_name: back-login
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    command: python /app/manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    container_name: front-vite
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Evitar conflictos con node_modules en el host
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
