services:
  web:
    build: .
    container_name: back-login
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    command: python /app/manage.py runserver 0.0.0.0:8000