# Generated by Django 5.1.6 on 2025-03-02 20:25

import users.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='icon',
            field=models.ImageField(storage=users.storage.CleanFileNameStorage(), upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(storage=users.storage.CleanFileNameStorage(), upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=users.storage.CleanFileNameStorage(), upload_to='videos/'),
        ),
    ]
